[package]
name = "dice-mfg"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive", "env"] }
dice-mfg-msgs = { path = "../dice-mfg-msgs" }
env_logger = "0.9"
log = "0.4"
pem = "1"
serialport = "4"
string-error = "0.1"
zerocopy = "0.6"
